[workspace]
channels = ["conda-forge"]
description = "Add a short description here"
name = "rts-docs"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]
install = { cmd = ["pnpm", "install"] }
build = { cmd = ["pnpm", "build"], depends-on = ["install"] }
start = { cmd = ["pnpm", "start"], depends-on = ["build"] }

[dependencies]
nodejs = ">=24.12.0,<24.13"
pnpm = ">=10.26.1,<11"
